services:
  - type: web
    name: she-can-r1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_KEY
        generateValue: true
      - key: DB_PATH
        value: submissions.db
  
